from ..base import *
from .eseriesbase import *


class ESeriesProductCategories(ESeriesApiResource, ListableApiResource, CreateableApiResource, UpdateableApiResource, DeleteableApiResource):
    resource_name = "categories"


example = {
    "id": 166927253,
    "orderBy": 10,
    "name": "Special Features",
    "nameTranslated": {"en": "Special Features"},
    "url": "https://store101812061.company.site/products/Special-Features-c166927253",
    "autogeneratedSlug": "special-features",
    "customSlug": "",
    "productCount": 7,
    "description": "",
    "descriptionTranslated": {"en": ""},
    "enabled": True,
    "isSampleCategory": False,
    "seoTitle": "Special Features",
    "seoTitleTranslated": {"en": "Special Features"},
    "seoDescription": "",
    "seoDescriptionTranslated": {"en": ""},
    "alt": {"main": "Special Features"},
    "json": {
        "id": 166927253,
        "orderBy": 10,
        "name": "Special Features",
        "nameTranslated": {"en": "Special Features"},
        "url": "https://store101812061.company.site/products/Special-Features-c166927253",
        "autogeneratedSlug": "special-features",
        "customSlug": "",
        "productCount": 7,
        "description": "",
        "descriptionTranslated": {"en": ""},
        "enabled": True,
        "isSampleCategory": False,
        "seoTitle": "Special Features",
        "seoTitleTranslated": {"en": "Special Features"},
        "seoDescription": "",
        "seoDescriptionTranslated": {"en": ""},
        "alt": {"main": "Special Features"},
        "json": {...},
    },
}
