CREATE TABLE `webscrapes` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `best_match_score` float(20,17) DEFAULT NULL,
  `retail_systemID` varchar(14) DEFAULT NULL,
  `is_match` int DEFAULT NULL,
  `best_match` int DEFAULT NULL,
  `_web_scraper_order` varchar(18) DEFAULT NULL,
  `web_scraper_start_url` varchar(256) DEFAULT NULL,
  `scrape_sourceID` int DEFAULT NULL,
  `sku` varchar(20) DEFAULT NULL,
  `ean` varchar(14) DEFAULT NULL,
  `product` varchar(128) DEFAULT NULL,
  `product_href` varchar(256) DEFAULT NULL,
  `title` varchar(128) DEFAULT NULL,
  `name` varchar(128) DEFAULT NULL,
  `vintage` int DEFAULT NULL,
  `producer` varchar(128) DEFAULT NULL,
  `brand` varchar(128) DEFAULT NULL,
  `price` float(8,2) DEFAULT NULL,
  `msrp` float(8,2) DEFAULT NULL,
  `sale` float(8,2) DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `region` varchar(64) DEFAULT NULL,
  `subregion` varchar(64) DEFAULT NULL,
  `description` blob,
  `description_html` blob,
  `image_src` varchar(256) DEFAULT NULL,
  `size` varchar(12) DEFAULT NULL,
  `alcohol` varchar(12) DEFAULT NULL,
  `closure` varchar(12) DEFAULT NULL,
  `sustainable` varchar(12) DEFAULT NULL,
  `category` varchar(12) DEFAULT NULL,
  `varietal` varchar(64) DEFAULT NULL,
  `varietal_1` varchar(64) DEFAULT NULL,
  `varietal_2` varchar(64) DEFAULT NULL,
  `varietal_3` varchar(64) DEFAULT NULL,
  `varietal_4` varchar(64) DEFAULT NULL,
  `varietal_5` varchar(64) DEFAULT NULL,
  `varietal_6` varchar(64) DEFAULT NULL,
  `rating_source_1` varchar(64) DEFAULT NULL,
  `rating_score_1` varchar(3) DEFAULT NULL,
  `rating_detail_1` blob,
  `rating_html_1` blob,
  `rating_citation_1` varchar(64) DEFAULT NULL,
  `rating_source_2` varchar(64) DEFAULT NULL,
  `rating_score_2` varchar(3) DEFAULT NULL,
  `rating_detail_2` blob,
  `rating_html_2` blob,
  `rating_citation_2` varchar(64) DEFAULT NULL,
  `rating_source_3` varchar(64) DEFAULT NULL,
  `rating_score_3` varchar(3) DEFAULT NULL,
  `rating_detail_3` blob,
  `rating_html_3` blob,
  `rating_citation_3` varchar(64) DEFAULT NULL,
  `rating_source_4` varchar(64) DEFAULT NULL,
  `rating_score_4` varchar(3) DEFAULT NULL,
  `rating_detail_4` blob,
  `rating_html_4` blob,
  `rating_citation_4` varchar(64) DEFAULT NULL,
  `modified_date` varchar(28) DEFAULT NULL,
  `ModifiedTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CreateDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8055 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `webscrapes_sources` (
  `ID` int DEFAULT NULL,
  `URL` varchar(255) DEFAULT NULL,
  `storename` varchar(255) DEFAULT NULL,
  `image_extension` varchar(255) DEFAULT NULL,
  `image_quality_rank` varchar(255) DEFAULT NULL,
  `image_format` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wine_reviews` (
  `id` int NOT NULL AUTO_INCREMENT,
  `source` varchar(45) DEFAULT NULL,
  `initials` varchar(10) DEFAULT NULL,
  `rating` int DEFAULT NULL,
  `review_detail` longtext,
  `review_html` longtext,
  `wine_itemID` int DEFAULT NULL,
  `wine_systemSKU` varchar(15) DEFAULT NULL,
  `review_vintage` varchar(4) DEFAULT NULL,
  `url` varchar(256) DEFAULT NULL,
  `ModifiedTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=330 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
